theme: minima
title: Austin Marchesani's Research Portfolio
author: Austin Marchesani
email: austin12@cfu.net
description: > # this means to ignore newlines until "baseurl:"
  This is where I will showcase all of my projects for my MSBA program along with
  my work as a data analyst for the University of Iowa Baseball Team.

# social links
twitter_username: amarchesani12 # DO NOT include the @ character, or else the build will fail!
github_username:  amarchesani12 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
